---
title: "TÜRKİYE’DE OTOMOBİL SATIN ALMA TERCİHLERİNİ ETKİLEYEN FAKTÖRELER"
author: 
  - Yusuf Kozal[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa-tr.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{turkish}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== NOTLAR ================================= -->
<!-- ======================================================================= -->
[^1]: 18080771, [Github Repo](https://github.com/yusuf2837/arasinav)



# Giriş
Türkiye’de satılan otomobil markaların, sahip olduğu modellerin kendi içinde veya diğer markalar arasında tercih sebeplerini markalar ve tüketiciler açısından incelediğim bu projede, Türkiye’de 202 yılı boyunca bütün otomobil firmalarının bütün modellerinin kaç adet satıldığı bilgisini içeren veriyi ilgili bir analiz firmasıyla (EBS Danışmanlık) iletişime geçerek edindim. Veri setini Türkiye’de en çok satış adedine sahip ilk 10 otomobil markasına indirgedikten sonra bu veriye çalışmamın amacına uygun gerekli değişkenleri eklemek için bu firmaların internet sitelerine girip mevzubahis araçların teknik özellikleri (motor hacmi, motor tipi, yakıt tüketimi ve emisyon verileri gibi) ve en düşük ve en yüksek donanıma sahip opsiyonlarının fiyatlarını ekleyerek en doğru sonuca varabileceğim 155 gözlem ve 30 değişken sayısına sahip veri setimi oluşturdum.

Bu çalışmada çalışmanın amacına yönelik olarak;

Otomobillerin, aynı modelin farklı versiyonlarında, farklı markaların benzer özelliklere sahip modellerinde fiyatlandırma konusunda ortaya çıkan sorunların çözümü ve bunların tüketici tercihlerini ne yönde etkilediği veya tüketici tercihlerinden etkilenip etkilenmediği araştırılmıştır. [@ohta1976automobile]

Otomobillerin bu tercihleri etkileyen faktörlerin başında gelen fiyat ve yakıt tüketimi gibi faktörlerin teknik özelliklerle beraber sınanmasıyla ortaya çıkan fiyat performans değerlerine göre veya yakıt fiyatlarının değişmesiyle otomobil satın alma tercihleri nasıl değişmiştir? Sorusuna cevap aranmıştır. [@busse2009pain] [@icsbilir2014turkiye]

Türkiye pazarında satılan araçların yerli üretim veya ithal olmasının araç teknik özellikleri açısında karşılaştırılıp tüketici açısından verimlilik farkı değerlendirilecektir. [@yilmaz2010turk]


## Çalışmanın Amacı
Türkiye’de satış rakamlarına göre ilk 10 otomobil markasına ait fiyatlar, satılan otomobil sayısı, teknik özellikler baz alınarak otomobil tüketicilerinin tercihlerini etkileyen faktörleri ve bu faktörlerin bu tercihleri ne oranda etkilediğini ölçmek ve bu söz konusu otomobil marka ve modellerinin karşılaştırma ve sıralamasının yapılması amacıyla bu verilerin doğrultusunda analiz yapmak ve bulunan istatistikleri yorumlamak.

Bu çalışmada göz önüne bulunduracağım ve elimdeki veriler doğrultusunda sınayacağım otomobil tüketimini etkileyen faktörler başta ekonomik sebepler olan araçların fiyatları ve bu fiyatlarla orantılı olarak belirttiğim teknik özelliklerin içinde bulunan performans ölçütleriyle marka ve modellerin fiyat performans açısından karşılaştırılması. İkinci ekonomik etmen olan ve yine kullandığım verilerde doğrudan bulunan yakıt tüketiminin değerlendirilmesi. Satılan araçların menşelerine göre veya üretimin bizim ülkemiz açısından bakıldığında yerli ürerim araçların mı yoksa ithal olarak ülkeye giren araçların mı daha çok tercih edildiğinin değerlendirilmesi. Bunların dışında tüketici tercihlerinin hangi değişkenlere bağlı olduğunu ölçmek amacıyla araç özelliklerini içeren verilerin satılan araç sayısı verileriyle oranlanarak modeller arasında bir kıyaslama yapılması amaçlanmaktadır.

Çalışmanın önemi ise otomobil firmaları açısından hedefledikleri satış rakamlarına ulaşmak için uygulamaları gereken yöntemleri tespit etmek, otomobil tüketicileri açısından ise araç fiyatlarının ve özelliklerinin karşılaştırılması açısından verimli bir istatistik analizi kaynağı elde etmektir.


## Literatür 
M Ohta ve Z Griliches'e göre "Bu kadar sınırlı kaynaklarla sonuca ulaşmak için söz konusu mal hakkında çok detaylı bilgi gerekir. Çok sayıda iyi veri ve modelin birçok olası alternatif spesifikasyonuna göre kişinin vardığı sonuçların sağlamlığının ayrıntılı bir analizini. Aşağıda, ele alıyoruz. Otomobil fiyatlarının analizinde birkaç sıkça sorulan konu, arasındaki fiyat farklılıklarını açıklamada “markaların” veya “markaların rolünün” etkili olduğu gibi farklı otomobil modellerinin, ek özellikleri, İkinci el araba fiyat analizlerinden elde edilen sonuçlar ve elde edilecek kazançlar, bir malın ilgili niteliklerini tanımlarken fiziksel (spesifikasyon) özellikler yerine performansı etkileyen diğer değişkenler..." [@ohta1976automobile] Bu çalışma marka sadakati dışında ürünlerin spesifik özelliklerini de araştırmasına dahil ederek, çalışmamızda inceleyebileceğimiz kapsamlı bir kaynak olarak göze çarpıyor.

MR Busse, CR Knittel, F Zettelmeyer ise yakıt tüketimi üzerine çalışmalarıyla çalışmamdaki yakıt tüketimi gibi bizim gibi enerji ve yakıt fiyatlarının yüksek olduğu bir ülkede tüketicilerin taşıt talebini etkileyen en önemli değişkenlerden birini değerlendiriyor. Yakıt tüketiminin otomobil talebinde nasıl bir tercih sebebi olup olmadığını araştırıyor. Bizim de çalışmamızda önemli bir değişken olarak ele alacağımız yakıt tüketimi noktasında çalışmamıza büyük fayda sunacağını düşünüyorum. "ABD'de 1999'da 1 dolara yakın olan benzin fiyatlarının 2008'de zirve yaparak 4 dolara yükselmesi, tüketiciler için otomobil kullanmanın maliyetini çok fazla arttırması sebebiyle tüketiciler, satın aldıkları otomobilleri değiştirerek benzin fiyatındaki değişikliklere uyum sağladılar. Bu etkileri hem yeni hem de kullanılmış araba pazarlarında araştırdık. Bunun sonucunda benzin fiyatındaki 1 dolarlık artışın, yakıtı en çok ve en az verimli kullanan çeyreklerin pazar paylarını değiştirdiğini gözlemledik yakıt tüketiminin otomobil kullanımında +%20 veya -%24 yeni araba sayısı gibi bir etkiye sahip olduğunu gözlemledik. Buna karşılık, aynı benzin fiyatındaki artış değişimi, ikinci el arabaların yakıt tasarrufu en yüksek ve en az olan çeyreklerinin pazar payları sırasıyla yalnızca %3 ve -%7 oldu. Benzin fiyatlarındaki değişikliklerin, yakıtı en verimli şekilde kullanan otomobillerin nispi fiyatlar düzeyini de değiştirdiğini bulduk. Çeyreklik ve yakıt açısından en az verimli olan çeyrekteki arabalar: sıfır arabalar için, yakıt tasarruflu için nispi fiyat artışı, benzin fiyatlarındaki 1 dolarlık artış için arabalar 363 dolar; ikinci el arabalar için 2839 dolar. Dolayısıyla dengenin ayarlanması yakıt tüketiminden kanyaklı araç kullanım maliyetindeki değişikliklere yanıt olarak pazar payları ve fiyatlar, sıfır ve kullanılan pazarlar Yeni otomobil pazarında, düzeltme öncelikle pazar paylarında olurken, ikinci el otomobil pazarında ikinci el araba pazarı ayarlaması öncelikle yakıt fiyatlarıyla yakından ilişkilidir. Benzinin maliyetindeki farkın sıfır ve ikinci el otomobil pazarlarını etkilemesi, arz özelliklerindeki spesifik diğer araç özelliklerinde farklılıklarıyla açıklanabilir."[@busse2009pain]
MR Busse, CR Knittel, F Zettelmeyer'in çalışmalarının sonucu olan bu araştırma bizimde tüketici talebini ele alırken yakıt tüketimi değişkenimizin etkisinin incelememizde bizlere büyük bir katkı sağlayacağını düşündüğüm bir çalışma. 

İşbilir ise 2011 yılında ülkemizdeki verileri ele alarak hazırladığı çalışmasında yakıt tipi silindir hacmi gibi değişkenlerin frekans değerleri ile vardığı sonuçlar şu şekilde "2011 yılı içerisinde toplam 592.396 araç satışı gerçekleşmiştir. En fazla araç satışı 173.806 adet ile 1500cc – 1599cc silindir hacminde görülmekte, %29.3 ile en büyük payı almaktadır. İkinci sırayı 1300cc – 1399cc silindir hacimli araçlar takip etmektedir, buna göre satış adeti 128.512 iken genele oranı %21.7 ‘dir. En düşük araç satışı ise 13.131 adet ile 2000cc ve üzeri silindir hacminde görülmektedir. Bunun oranı ise %2.2‟dir." [@icsbilir2014turkiye] bu çalışmasıyla incelmede bulunacağım değişkenlerin yorumlanması noktasında çalışmamıza büyük ölçüde ışık tutacaktır.

N YILMAZ, İ KARAKADILAR ise yine Türkiye’de otomobil pazarı üzerine yaptığı çalışmalarıyla "Türk otomobil pazarında en çok satılan yerli üretim araba modelleriyle ithal araçlar arasında tüketiciye sunulan teknik özellikler ile tüketiciye yüklenen külfet açısından bir verimlilik farkının bulunup bulunmadığını ortaya koymak." [@yilmaz2010turk] amacıyla yaptıkları çalışmalarıyla incelememize daha geniş bir perspektifle bakmamızı sağlayacak ek bir kaynak oluşturmakta.





\newpage
# Kaynakça {#references}
<div id="refs"></div>

